apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: application
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: nginx
          image: omarvides/backend-color-api:latest
          resources:
            limits:
              memory: "50Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
